module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,jsx,ts,tsx}', './index.html'],
  theme: {
    extend: {
      colors: {
        'primary':                  '#2d7235',
        'primary-dim':              '#1f652a',
        'primary-fixed':            '#aaf4a8',
        'primary-fixed-dim':        '#9de69b',
        'on-primary':               '#ffffff',
        'on-primary-fixed':         '#004a15',
        'on-primary-container':     '#175e24',
        'primary-container':        '#aaf4a8',
        'secondary':                '#865c00',
        'secondary-dim':            '#765100',
        'secondary-fixed':          '#ffc96e',
        'secondary-fixed-dim':      '#ffb622',
        'secondary-container':      '#ffc96e',
        'on-secondary':             '#ffffff',
        'on-secondary-container':   '#604100',
        'tertiary':                 '#4b6c4c',
        'tertiary-dim':             '#3f6041',
        'tertiary-container':       '#d7fed5',
        'on-tertiary':              '#ffffff',
        'on-tertiary-container':    '#426344',
        'background':               '#fffcf1',
        'surface':                  '#fffcf1',
        'surface-container':        '#f6f4e7',
        'surface-container-low':    '#fcfaee',
        'surface-container-high':   '#f0eee1',
        'surface-container-highest':'#eae9db',
        'surface-container-lowest': '#ffffff',
        'surface-dim':              '#e4e3d4',
        'on-surface':               '#383831',
        'on-surface-variant':       '#65655c',
        'outline':                  '#818178',
        'outline-variant':          '#bbbaaf',
        'error':                    '#be2d06',
        'error-container':          '#f95630',
        'on-error':                 '#ffffff',
      },
      borderRadius: {
        DEFAULT:  '1rem',
        lg:       '2rem',
        xl:       '3rem',
        full:     '9999px',
      },
      fontFamily: {
        sans:     ['Manrope', 'sans-serif'],
        headline: ['Manrope', 'sans-serif'],
        body:     ['Manrope', 'sans-serif'],
        label:    ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
