import { supabase } from './supabase'
import { sanitizeForMarketplace, sanitizeForProfile, isUnlocked } from './sanitizeCandidate'

const FAKE_CANDIDATES = [
  // ── Technology (8) ────────────────────────────────────────
  { role_applied_for:'Senior Backend Engineer', seniority_level:'Senior', years_experience:7, location_city:'Sydney', location_country:'Australia', preferred_work_type:'Remote', skills:['Go','PostgreSQL','Kubernetes','gRPC'], interview_stage_reached:'Final round', interviews_completed:4, fee_percentage:8, referring_company:'TechFlow', strengths:'Led migration of 2.4M user accounts to microservices, reducing p99 latency by 68%.', gaps:'Limited frontend experience.', feedback_summary:'Strong senior engineer with deep backend expertise.', recommendation:'Strong hire', why_not_hired:'Headcount freeze', salary_expectation_min:170000, salary_expectation_max:195000, industry:'Technology', status:'available', pii_redacted:true, source:'upload_form', full_name:'James Thornton', email:'james.thornton@test.com', current_employer:'Canva', current_job_title:'Senior Backend Engineer' },
  { role_applied_for:'Staff Frontend Engineer', seniority_level:'Lead', years_experience:9, location_city:'Brisbane', location_country:'Australia', preferred_work_type:'Remote', skills:['React','TypeScript','GraphQL','Next.js','Design Systems'], interview_stage_reached:'Final round', interviews_completed:5, fee_percentage:8, referring_company:'AI Talent Co', strengths:'Built design system adopted across 6 product teams. Deep React performance and a11y expertise.', gaps:'Less native mobile experience.', feedback_summary:'Exceptional frontend leader.', recommendation:'Strong hire', why_not_hired:'Role cancelled', salary_expectation_min:190000, salary_expectation_max:220000, industry:'Technology', status:'available', pii_redacted:true, source:'upload_form', full_name:'Lena Park', email:'lena.park@test.com', current_employer:'SafetyCulture', current_job_title:'Staff Frontend Engineer' },
  { role_applied_for:'DevOps/Cloud Engineer', seniority_level:'Senior', years_experience:8, location_city:'Perth', location_country:'Australia', preferred_work_type:'Remote', skills:['AWS','Terraform','Docker','Kubernetes','CI/CD'], interview_stage_reached:'Technical screen', interviews_completed:2, fee_percentage:8, referring_company:'TechFlow', strengths:'Built zero-downtime deployment pipeline. AWS SA certified.', gaps:'Less GCP/Azure multi-cloud experience.', feedback_summary:'Solid DevOps engineer with strong AWS depth.', recommendation:'Hire', why_not_hired:'Timing — project delayed', salary_expectation_min:160000, salary_expectation_max:185000, industry:'Technology', status:'available', pii_redacted:true, source:'upload_form', full_name:'Tom Nguyen', email:'tom.nguyen@test.com', current_employer:'Woodside Energy', current_job_title:'Senior Cloud Engineer' },
  { role_applied_for:'Junior Software Engineer', seniority_level:'Junior', years_experience:1, location_city:'Melbourne', location_country:'Australia', preferred_work_type:'Hybrid', skills:['Python','JavaScript','React','Git'], interview_stage_reached:'1st phone screen', interviews_completed:1, fee_percentage:6, referring_company:'GradTech', strengths:'Quick learner with strong CS fundamentals. Built full-stack project with 2k users.', gaps:'Needs mentorship and structured onboarding.', feedback_summary:'Promising junior with growth potential.', recommendation:'Hire', why_not_hired:'Better fit selected', salary_expectation_min:75000, salary_expectation_max:90000, industry:'Technology', status:'available', pii_redacted:true, source:'upload_form', full_name:'Aisha Mohammed', email:'aisha.m@test.com', current_employer:'University of Melbourne', current_job_title:'Graduate Developer' },
  { role_applied_for:'ML/AI Engineer', seniority_level:'Senior', years_experience:6, location_city:'Sydney', location_country:'Australia', preferred_work_type:'Hybrid', skills:['Python','PyTorch','MLOps','Kubernetes','Spark'], interview_stage_reached:'2nd round', interviews_completed:3, fee_percentage:9, referring_company:'DataHire', strengths:'Deployed recommendation system serving 10M+ daily predictions. Published 3 NeurIPS papers.', gaps:'Could improve production engineering practices.', feedback_summary:'Strong ML engineer with research background.', recommendation:'Strong hire', why_not_hired:'Salary mismatch', salary_expectation_min:185000, salary_expectation_max:210000, industry:'Technology', status:'available', pii_redacted:true, source:'upload_form', full_name:'Raj Patel', email:'raj.patel@test.com', current_employer:'Atlassian', current_job_title:'Senior ML Engineer' },
  { role_applied_for:'Security Engineer', seniority_level:'Senior', years_experience:7, location_city:'Canberra', location_country:'Australia', preferred_work_type:'On-site', skills:['Penetration Testing','AWS Security','SIEM','Incident Response'], interview_stage_reached:'Final round', interviews_completed:4, fee_percentage:8, referring_company:'CyberTalent', strengths:'Led SOC 2 certification. Discovered critical vuln saving $2M+ in potential damages.', gaps:'Less cloud-native security tooling.', feedback_summary:'Thorough security professional.', recommendation:'Strong hire', why_not_hired:'Headcount freeze', salary_expectation_min:175000, salary_expectation_max:200000, industry:'Technology', status:'available', pii_redacted:true, source:'upload_form', full_name:'Elena Volkov', email:'elena.v@test.com', current_employer:'ASD Contractor', current_job_title:'Senior Security Engineer' },
  { role_applied_for:'Platform Engineer', seniority_level:'Mid', years_experience:4, location_city:'Melbourne', location_country:'Australia', preferred_work_type:'Remote', skills:['Go','Kubernetes','ArgoCD','Prometheus','Terraform'], interview_stage_reached:'Technical screen', interviews_completed:2, fee_percentage:8, referring_company:'DevHouse', strengths:'Reduced deployment time by 80% with new CI/CD pipeline.', gaps:'Needs more large-scale distributed systems experience.', feedback_summary:'Growing platform engineer with solid fundamentals.', recommendation:'Hire', why_not_hired:'Better fit selected', salary_expectation_min:130000, salary_expectation_max:150000, industry:'Technology', status:'available', pii_redacted:true, source:'upload_form', full_name:'Dylan Carter', email:'dylan.c@test.com', current_employer:'REA Group', current_job_title:'Platform Engineer' },
  { role_applied_for:'Mobile Engineer', seniority_level:'Senior', years_experience:6, location_city:'Sydney', location_country:'Australia', preferred_work_type:'Hybrid', skills:['React Native','Swift','Kotlin','GraphQL'], interview_stage_reached:'Final round', interviews_completed:4, fee_percentage:8, referring_company:'AppTalent', strengths:'Shipped apps with 4.8+ star ratings and 500k+ downloads.', gaps:'Less backend experience.', feedback_summary:'Strong mobile specialist.', recommendation:'Strong hire', why_not_hired:'Offer declined', salary_expectation_min:165000, salary_expectation_max:190000, industry:'Technology', status:'unlocked', pii_redacted:true, source:'upload_form', full_name:'Mei Lin', email:'mei.lin@test.com', current_employer:'Afterpay', current_job_title:'Senior Mobile Engineer' },
  // ── Product & Design (4) ──────────────────────────────────
  { role_applied_for:'Product Manager', seniority_level:'Mid', years_experience:5, location_city:'Melbourne', location_country:'Australia', preferred_work_type:'Hybrid', skills:['Product Strategy','SQL','Figma','A/B Testing'], interview_stage_reached:'Technical screen', interviews_completed:3, fee_percentage:8, referring_company:'DevHouse', strengths:'Built B2B SaaS product from 0 to 40k+ users in 18 months.', gaps:'Could strengthen data pipeline knowledge.', feedback_summary:'Solid mid-level PM with strong execution.', recommendation:'Hire', why_not_hired:'Better fit selected', salary_expectation_min:140000, salary_expectation_max:160000, industry:'Product & Design', status:'available', pii_redacted:true, source:'upload_form', full_name:'Sarah Chen', email:'sarah.chen@test.com', current_employer:'Atlassian', current_job_title:'Product Manager' },
  { role_applied_for:'Head of Product', seniority_level:'Director', years_experience:12, location_city:'Sydney', location_country:'Australia', preferred_work_type:'On-site', skills:['Product Strategy','Team Leadership','OKRs','Roadmapping'], interview_stage_reached:'Final round', interviews_completed:5, fee_percentage:10, referring_company:'ExecSearch', strengths:'Scaled product org from 3 to 18 PMs. Drove 40% revenue growth.', gaps:null, feedback_summary:'Exceptional product leader for Series B+.', recommendation:'Strong hire', why_not_hired:'Offer declined', salary_expectation_min:260000, salary_expectation_max:310000, industry:'Product & Design', status:'available', pii_redacted:true, source:'upload_form', full_name:'Michael Torres', email:'michael.t@test.com', current_employer:'Canva', current_job_title:'VP Product' },
  { role_applied_for:'UX/UI Designer', seniority_level:'Senior', years_experience:7, location_city:'Melbourne', location_country:'Australia', preferred_work_type:'Remote', skills:['Figma','User Research','Design Systems','Prototyping'], interview_stage_reached:'Final round', interviews_completed:4, fee_percentage:8, referring_company:'DesignHire', strengths:'Created design system used by 200+ engineers. Increased conversion by 34%.', gaps:'Less mobile-first B2C experience.', feedback_summary:'Strong senior designer with systems thinking.', recommendation:'Strong hire', why_not_hired:'Role cancelled', salary_expectation_min:150000, salary_expectation_max:175000, industry:'Product & Design', status:'available', pii_redacted:true, source:'upload_form', full_name:'Olivia Brennan', email:'olivia.b@test.com', current_employer:'Culture Amp', current_job_title:'Senior Product Designer' },
  { role_applied_for:'UX Researcher', seniority_level:'Mid', years_experience:4, location_city:'Brisbane', location_country:'Australia', preferred_work_type:'Hybrid', skills:['User Testing','Survey Design','Analytics','Figma'], interview_stage_reached:'2nd round', interviews_completed:2, fee_percentage:7, referring_company:'DesignHire', strengths:'Conducted 200+ user interviews. Research led to 28% churn reduction.', gaps:'Needs more quant research experience.', feedback_summary:'Empathetic researcher with strong qual skills.', recommendation:'Hire', why_not_hired:'Better fit selected', salary_expectation_min:110000, salary_expectation_max:130000, industry:'Product & Design', status:'available', pii_redacted:true, source:'upload_form', full_name:'Hannah Liu', email:'hannah.l@test.com', current_employer:'Xero', current_job_title:'UX Researcher' },
  // ── Data & Analytics (4) ──────────────────────────────────
  { role_applied_for:'Data Engineer', seniority_level:'Senior', years_experience:6, location_city:'Sydney', location_country:'Australia', preferred_work_type:'Hybrid', skills:['Python','Spark','Airflow','dbt','BigQuery'], interview_stage_reached:'2nd round', interviews_completed:3, fee_percentage:10, referring_company:'CloudOps', strengths:'Designed pipeline processing 50TB+ daily.', gaps:'Could improve stakeholder communication.', feedback_summary:'Reliable data engineer with strong technical depth.', recommendation:'Hire', why_not_hired:'Salary mismatch', salary_expectation_min:155000, salary_expectation_max:175000, industry:'Data & Analytics', status:'available', pii_redacted:true, source:'upload_form', full_name:'Marcus Webb', email:'marcus.webb@test.com', current_employer:'Zip Co', current_job_title:'Senior Data Engineer' },
  { role_applied_for:'Data Scientist', seniority_level:'Senior', years_experience:5, location_city:'Melbourne', location_country:'Australia', preferred_work_type:'Remote', skills:['Python','R','TensorFlow','SQL','Tableau'], interview_stage_reached:'Final round', interviews_completed:4, fee_percentage:8, referring_company:'DataHire', strengths:'Built propensity model increasing upsell by $4.2M annually.', gaps:'Less production ML deployment experience.', feedback_summary:'Strong analytical thinker with business impact.', recommendation:'Strong hire', why_not_hired:'Timing — project delayed', salary_expectation_min:145000, salary_expectation_max:170000, industry:'Data & Analytics', status:'available', pii_redacted:true, source:'upload_form', full_name:'Yuki Tanaka', email:'yuki.t@test.com', current_employer:'CommBank', current_job_title:'Senior Data Scientist' },
  { role_applied_for:'Analytics Engineer', seniority_level:'Mid', years_experience:3, location_city:'Sydney', location_country:'Australia', preferred_work_type:'Hybrid', skills:['dbt','SQL','Looker','Python','BigQuery'], interview_stage_reached:'Technical screen', interviews_completed:2, fee_percentage:7, referring_company:'DataHire', strengths:'Built self-serve analytics layer used by 50+ stakeholders.', gaps:'Needs real-time streaming experience.', feedback_summary:'Growing analytics engineer with strong SQL.', recommendation:'Hire', why_not_hired:'Better fit selected', salary_expectation_min:120000, salary_expectation_max:140000, industry:'Data & Analytics', status:'available', pii_redacted:true, source:'upload_form', full_name:'Sam O Brien', email:'sam.ob@test.com', current_employer:'Seek', current_job_title:'Analytics Engineer' },
  { role_applied_for:'Head of Data', seniority_level:'Director', years_experience:11, location_city:'Melbourne', location_country:'Australia', preferred_work_type:'On-site', skills:['Team Leadership','Data Strategy','ML','BigQuery','Spark'], interview_stage_reached:'Final round', interviews_completed:5, fee_percentage:10, referring_company:'ExecSearch', strengths:'Built data team from 2 to 15. Established data governance framework.', gaps:null, feedback_summary:'Visionary data leader.', recommendation:'Strong hire', why_not_hired:'Headcount freeze', salary_expectation_min:240000, salary_expectation_max:290000, industry:'Data & Analytics', status:'placed', pii_redacted:true, source:'upload_form', full_name:'Ankit Gupta', email:'ankit.g@test.com', current_employer:'Xero', current_job_title:'Head of Data & Analytics' },
  // ── Sales & Revenue (4) ───────────────────────────────────
  { role_applied_for:'Account Executive', seniority_level:'Mid', years_experience:4, location_city:'Sydney', location_country:'Australia', preferred_work_type:'On-site', skills:['Salesforce','MEDDIC','Enterprise Sales','Negotiation'], interview_stage_reached:'Final round', interviews_completed:4, fee_percentage:8, referring_company:'SalesHire', strengths:'Closed $2.8M ARR in first year. 142% quota attainment.', gaps:'Less PLG sales motion experience.', feedback_summary:'High-performing AE with strong enterprise skills.', recommendation:'Strong hire', why_not_hired:'Offer declined', salary_expectation_min:130000, salary_expectation_max:160000, industry:'Sales & Revenue', status:'available', pii_redacted:true, source:'upload_form', full_name:'Jordan Blake', email:'jordan.b@test.com', current_employer:'Salesforce', current_job_title:'Account Executive' },
  { role_applied_for:'Head of Sales', seniority_level:'Director', years_experience:10, location_city:'Melbourne', location_country:'Australia', preferred_work_type:'On-site', skills:['Team Leadership','Revenue Operations','Forecasting','Enterprise Sales'], interview_stage_reached:'Final round', interviews_completed:5, fee_percentage:10, referring_company:'ExecSearch', strengths:'Scaled ANZ revenue from $5M to $28M in 3 years. Built team of 22.', gaps:null, feedback_summary:'Proven sales leader for scale-up phase.', recommendation:'Strong hire', why_not_hired:'Headcount freeze', salary_expectation_min:250000, salary_expectation_max:300000, industry:'Sales & Revenue', status:'available', pii_redacted:true, source:'upload_form', full_name:'Chris Whitfield', email:'chris.w@test.com', current_employer:'HubSpot', current_job_title:'Regional Director ANZ' },
  { role_applied_for:'SDR/BDR', seniority_level:'Junior', years_experience:1, location_city:'Sydney', location_country:'Australia', preferred_work_type:'Hybrid', skills:['Cold Outreach','Salesforce','LinkedIn Sales Nav','Prospecting'], interview_stage_reached:'1st phone screen', interviews_completed:1, fee_percentage:6, referring_company:'GradTech', strengths:'Generated 45 qualified meetings in first quarter.', gaps:'Needs more discovery call structure.', feedback_summary:'Promising early-career SDR.', recommendation:'Hire', why_not_hired:'Better fit selected', salary_expectation_min:70000, salary_expectation_max:85000, industry:'Sales & Revenue', status:'available', pii_redacted:true, source:'upload_form', full_name:'Zara Hussein', email:'zara.h@test.com', current_employer:'Airtasker', current_job_title:'Business Development Rep' },
  { role_applied_for:'Revenue Operations', seniority_level:'Senior', years_experience:6, location_city:'Melbourne', location_country:'Australia', preferred_work_type:'Remote', skills:['Salesforce Admin','HubSpot','SQL','Looker','Process Design'], interview_stage_reached:'2nd round', interviews_completed:3, fee_percentage:8, referring_company:'SalesHire', strengths:'Reduced sales cycle by 22% through pipeline optimization.', gaps:'Less international market expansion experience.', feedback_summary:'Strong RevOps professional.', recommendation:'Hire', why_not_hired:'Timing — project delayed', salary_expectation_min:145000, salary_expectation_max:165000, industry:'Sales & Revenue', status:'available', pii_redacted:true, source:'upload_form', full_name:'Natalie Russo', email:'natalie.r@test.com', current_employer:'Culture Amp', current_job_title:'Senior RevOps Manager' },
  // ── Marketing & Growth (3) ────────────────────────────────
  { role_applied_for:'Head of Growth', seniority_level:'Director', years_experience:11, location_city:'Melbourne', location_country:'Australia', preferred_work_type:'On-site', skills:['Growth Strategy','Paid Acquisition','Analytics','Team Leadership'], interview_stage_reached:'Final round', interviews_completed:4, fee_percentage:8, referring_company:'HireRight', strengths:'Scaled user acquisition from 10k to 2M MAU.', gaps:null, feedback_summary:'Exceptional growth leader.', recommendation:'Strong hire', why_not_hired:'Offer declined', salary_expectation_min:220000, salary_expectation_max:260000, industry:'Marketing & Growth', status:'available', pii_redacted:true, source:'upload_form', full_name:'Priya Sharma', email:'priya.s@test.com', current_employer:'Culture Amp', current_job_title:'Head of Growth' },
  { role_applied_for:'Performance Marketing', seniority_level:'Mid', years_experience:4, location_city:'Sydney', location_country:'Australia', preferred_work_type:'Hybrid', skills:['Google Ads','Meta Ads','Analytics','CRO','SQL'], interview_stage_reached:'2nd round', interviews_completed:3, fee_percentage:7, referring_company:'MarketHire', strengths:'Managed $3M+ annual ad spend with 4.2x ROAS.', gaps:'Less B2B demand gen experience.', feedback_summary:'Strong performance marketer for B2C.', recommendation:'Hire', why_not_hired:'Better fit selected', salary_expectation_min:115000, salary_expectation_max:135000, industry:'Marketing & Growth', status:'available', pii_redacted:true, source:'upload_form', full_name:'Ben Taylor', email:'ben.t@test.com', current_employer:'Koala', current_job_title:'Performance Marketing Lead' },
  { role_applied_for:'Content/SEO', seniority_level:'Mid', years_experience:5, location_city:'Brisbane', location_country:'Australia', preferred_work_type:'Remote', skills:['SEO','Content Strategy','Ahrefs','Google Analytics','Copywriting'], interview_stage_reached:'Technical screen', interviews_completed:2, fee_percentage:7, referring_company:'MarketHire', strengths:'Grew organic traffic 340% in 12 months.', gaps:'Less video content experience.', feedback_summary:'Strong content strategist with SEO depth.', recommendation:'Hire', why_not_hired:'Role cancelled', salary_expectation_min:110000, salary_expectation_max:130000, industry:'Marketing & Growth', status:'available', pii_redacted:true, source:'upload_form', full_name:'Grace Kim', email:'grace.k@test.com', current_employer:'Envato', current_job_title:'Content & SEO Lead' },
  // ── Finance & FinTech (3) ─────────────────────────────────
  { role_applied_for:'Financial Analyst', seniority_level:'Mid', years_experience:4, location_city:'Sydney', location_country:'Australia', preferred_work_type:'Hybrid', skills:['Financial Modelling','Excel','SQL','Power BI','Forecasting'], interview_stage_reached:'2nd round', interviews_completed:3, fee_percentage:7, referring_company:'FinTalent', strengths:'Built 3-year financial model adopted by board. Identified $1.2M cost savings.', gaps:'Less fundraising experience.', feedback_summary:'Detail-oriented analyst with strong modelling.', recommendation:'Hire', why_not_hired:'Salary mismatch', salary_expectation_min:110000, salary_expectation_max:130000, industry:'Finance & FinTech', status:'available', pii_redacted:true, source:'upload_form', full_name:'David Okonkwo', email:'david.o@test.com', current_employer:'Afterpay', current_job_title:'Financial Analyst' },
  { role_applied_for:'CFO/Finance Director', seniority_level:'VP/C-suite', years_experience:15, location_city:'Sydney', location_country:'Australia', preferred_work_type:'On-site', skills:['Financial Strategy','M&A','Fundraising','Board Reporting','Team Leadership'], interview_stage_reached:'Final round', interviews_completed:5, fee_percentage:12, referring_company:'ExecSearch', strengths:'Led $50M Series C raise. Managed $200M+ P&L. IPO experience.', gaps:null, feedback_summary:'Board-ready CFO for late-stage startups.', recommendation:'Strong hire', why_not_hired:'Headcount freeze', salary_expectation_min:300000, salary_expectation_max:380000, industry:'Finance & FinTech', status:'unlocked', pii_redacted:true, source:'upload_form', full_name:'Katherine Hartley', email:'katherine.h@test.com', current_employer:'Zip Co', current_job_title:'CFO' },
  { role_applied_for:'Risk & Compliance', seniority_level:'Senior', years_experience:8, location_city:'Melbourne', location_country:'Australia', preferred_work_type:'Hybrid', skills:['AML/CTF','AFSL Compliance','Risk Assessment','Regulatory Reporting'], interview_stage_reached:'Final round', interviews_completed:4, fee_percentage:9, referring_company:'FinTalent', strengths:'Built compliance framework for AFSL holder. Zero regulatory breaches in 3 years.', gaps:'Less crypto/DeFi regulation experience.', feedback_summary:'Thorough compliance professional.', recommendation:'Strong hire', why_not_hired:'Timing — project delayed', salary_expectation_min:160000, salary_expectation_max:185000, industry:'Finance & FinTech', status:'available', pii_redacted:true, source:'upload_form', full_name:'William Fong', email:'william.f@test.com', current_employer:'Macquarie Group', current_job_title:'Senior Compliance Manager' },
  // ── People & HR (3) ───────────────────────────────────────
  { role_applied_for:'Talent Acquisition', seniority_level:'Senior', years_experience:6, location_city:'Sydney', location_country:'Australia', preferred_work_type:'Hybrid', skills:['Full-cycle Recruiting','Employer Branding','ATS','Stakeholder Management'], interview_stage_reached:'2nd round', interviews_completed:3, fee_percentage:7, referring_company:'PeopleFirst', strengths:'Hired 120+ engineers in 18 months. Built referral program with 40% hit rate.', gaps:'Less executive search experience.', feedback_summary:'High-volume TA specialist.', recommendation:'Hire', why_not_hired:'Better fit selected', salary_expectation_min:125000, salary_expectation_max:145000, industry:'People & HR', status:'available', pii_redacted:true, source:'upload_form', full_name:'Amy Walsh', email:'amy.w@test.com', current_employer:'Canva', current_job_title:'Senior TA Partner' },
  { role_applied_for:'HR Business Partner', seniority_level:'Senior', years_experience:8, location_city:'Melbourne', location_country:'Australia', preferred_work_type:'On-site', skills:['Employee Relations','Performance Management','Change Management','L&D'], interview_stage_reached:'Final round', interviews_completed:4, fee_percentage:8, referring_company:'PeopleFirst', strengths:'Supported 400-person eng org through 2 reorgs. Reduced attrition by 18%.', gaps:'Less international HRBP work.', feedback_summary:'Experienced HRBP for scaling tech companies.', recommendation:'Strong hire', why_not_hired:'Headcount freeze', salary_expectation_min:150000, salary_expectation_max:175000, industry:'People & HR', status:'unlocked', pii_redacted:true, source:'upload_form', full_name:'Rachel Cooper', email:'rachel.c@test.com', current_employer:'Atlassian', current_job_title:'Senior HRBP' },
  { role_applied_for:'Chief People Officer', seniority_level:'VP/C-suite', years_experience:14, location_city:'Sydney', location_country:'Australia', preferred_work_type:'On-site', skills:['People Strategy','Culture','Executive Coaching','Org Design','DE&I'], interview_stage_reached:'Final round', interviews_completed:5, fee_percentage:12, referring_company:'ExecSearch', strengths:'Built people function for 3 companies from 50 to 500+. Glassdoor 3.2 to 4.6.', gaps:null, feedback_summary:'Transformational people leader.', recommendation:'Strong hire', why_not_hired:'Offer declined', salary_expectation_min:280000, salary_expectation_max:340000, industry:'People & HR', status:'placed', pii_redacted:true, source:'upload_form', full_name:'Deepa Nair', email:'deepa.n@test.com', current_employer:'Canva', current_job_title:'VP People' },
  // ── Operations (2) ────────────────────────────────────────
  { role_applied_for:'Operations Manager', seniority_level:'Mid', years_experience:5, location_city:'Adelaide', location_country:'Australia', preferred_work_type:'On-site', skills:['Process Improvement','Lean Six Sigma','ERP','Project Management'], interview_stage_reached:'2nd round', interviews_completed:3, fee_percentage:7, referring_company:'OpsHire', strengths:'Reduced fulfilment costs by 25% through process re-engineering.', gaps:'Less SaaS operations experience.', feedback_summary:'Efficient operations professional.', recommendation:'Hire', why_not_hired:'Better fit selected', salary_expectation_min:100000, salary_expectation_max:120000, industry:'Operations', status:'available', pii_redacted:true, source:'upload_form', full_name:'Luke Henderson', email:'luke.h@test.com', current_employer:'Kogan', current_job_title:'Operations Manager' },
  { role_applied_for:'COO', seniority_level:'VP/C-suite', years_experience:13, location_city:'Melbourne', location_country:'Australia', preferred_work_type:'On-site', skills:['Operational Strategy','Scaling','M&A Integration','Team Leadership'], interview_stage_reached:'Final round', interviews_completed:5, fee_percentage:12, referring_company:'ExecSearch', strengths:'Scaled operations from 100 to 800 employees across 4 countries.', gaps:null, feedback_summary:'Experienced COO for high-growth companies.', recommendation:'Strong hire', why_not_hired:'Headcount freeze', salary_expectation_min:290000, salary_expectation_max:350000, industry:'Operations', status:'available', pii_redacted:true, source:'upload_form', full_name:'Daniel Russo', email:'daniel.r@test.com', current_employer:'SafetyCulture', current_job_title:'COO' },
  // ── Customer Success (2) ──────────────────────────────────
  { role_applied_for:'Customer Success Manager', seniority_level:'Mid', years_experience:4, location_city:'Sydney', location_country:'Australia', preferred_work_type:'Hybrid', skills:['Account Management','Onboarding','Churn Prevention','Gainsight'], interview_stage_reached:'Final round', interviews_completed:4, fee_percentage:7, referring_company:'CSHire', strengths:'Managed $8M ARR book with 96% retention. NPS 72.', gaps:'Less enterprise account experience.', feedback_summary:'Reliable CSM with strong retention metrics.', recommendation:'Hire', why_not_hired:'Better fit selected', salary_expectation_min:105000, salary_expectation_max:125000, industry:'Customer Success', status:'available', pii_redacted:true, source:'upload_form', full_name:'Emily Zhang', email:'emily.z@test.com', current_employer:'Culture Amp', current_job_title:'Customer Success Manager' },
  { role_applied_for:'Head of CS', seniority_level:'Director', years_experience:9, location_city:'Melbourne', location_country:'Australia', preferred_work_type:'Hybrid', skills:['CS Strategy','Team Leadership','Revenue Retention','Gainsight'], interview_stage_reached:'Final round', interviews_completed:5, fee_percentage:9, referring_company:'CSHire', strengths:'Built CS team from 3 to 20. Improved NRR from 95% to 118%.', gaps:null, feedback_summary:'Strong CS leader driving revenue expansion.', recommendation:'Strong hire', why_not_hired:'Role cancelled', salary_expectation_min:200000, salary_expectation_max:240000, industry:'Customer Success', status:'unlocked', pii_redacted:true, source:'upload_form', full_name:'Jack Morrison', email:'jack.m@test.com', current_employer:'SafetyCulture', current_job_title:'Head of Customer Success' },
  // ── Legal & Compliance (2) ────────────────────────────────
  { role_applied_for:'General Counsel', seniority_level:'Director', years_experience:12, location_city:'Sydney', location_country:'Australia', preferred_work_type:'On-site', skills:['Corporate Law','IP','Employment Law','M&A','Privacy'], interview_stage_reached:'Final round', interviews_completed:5, fee_percentage:10, referring_company:'LegalHire', strengths:'Managed legal for $200M+ acquisition. IP portfolio of 15 patents.', gaps:null, feedback_summary:'Experienced GC for tech scale-ups.', recommendation:'Strong hire', why_not_hired:'Offer declined', salary_expectation_min:260000, salary_expectation_max:320000, industry:'Legal & Compliance', status:'placed', pii_redacted:true, source:'upload_form', full_name:'Sophie Anderson', email:'sophie.a@test.com', current_employer:'Xero', current_job_title:'General Counsel' },
  { role_applied_for:'Privacy/GDPR', seniority_level:'Senior', years_experience:6, location_city:'Melbourne', location_country:'Australia', preferred_work_type:'Remote', skills:['Privacy Law','GDPR','APPs','Data Governance','CIPP/E'], interview_stage_reached:'2nd round', interviews_completed:3, fee_percentage:8, referring_company:'LegalHire', strengths:'Led GDPR compliance across 12 markets. Zero regulatory incidents.', gaps:'Less US state privacy law experience.', feedback_summary:'Strong privacy specialist.', recommendation:'Hire', why_not_hired:'Timing — project delayed', salary_expectation_min:150000, salary_expectation_max:175000, industry:'Legal & Compliance', status:'available', pii_redacted:true, source:'upload_form', full_name:'Alex Petrov', email:'alex.p@test.com', current_employer:'Afterpay', current_job_title:'Senior Privacy Counsel' },
  // ── Mixed extras (5) ──────────────────────────────────────
  { role_applied_for:'QA/Test Engineer', seniority_level:'Mid', years_experience:4, location_city:'Hobart', location_country:'Australia', preferred_work_type:'Remote', skills:['Cypress','Playwright','Jest','CI/CD','API Testing'], interview_stage_reached:'Technical screen', interviews_completed:2, fee_percentage:7, referring_company:'TechFlow', strengths:'Built automated test suite covering 92% of critical paths. Reduced bug escape rate 60%.', gaps:'Less performance testing experience.', feedback_summary:'Thorough QA engineer.', recommendation:'Hire', why_not_hired:'Better fit selected', salary_expectation_min:110000, salary_expectation_max:130000, industry:'Technology', status:'available', pii_redacted:true, source:'upload_form', full_name:'Isla MacLeod', email:'isla.m@test.com', current_employer:'MYOB', current_job_title:'QA Engineer' },
  { role_applied_for:'Solutions Architect', seniority_level:'Lead', years_experience:10, location_city:'Sydney', location_country:'Australia', preferred_work_type:'Hybrid', skills:['AWS','System Design','Microservices','Java','Enterprise Architecture'], interview_stage_reached:'Final round', interviews_completed:4, fee_percentage:9, referring_company:'TechFlow', strengths:'Designed system handling 100k+ TPS. AWS Professional certified.', gaps:'Less hands-on coding recently.', feedback_summary:'Excellent architect for complex systems.', recommendation:'Strong hire', why_not_hired:'Salary mismatch', salary_expectation_min:200000, salary_expectation_max:240000, industry:'Technology', status:'unlocked', pii_redacted:true, source:'upload_form', full_name:'James Fitzgerald', email:'james.f@test.com', current_employer:'Atlassian', current_job_title:'Principal Solutions Architect' },
  { role_applied_for:'Brand Manager', seniority_level:'Senior', years_experience:7, location_city:'Melbourne', location_country:'Australia', preferred_work_type:'On-site', skills:['Brand Strategy','Creative Direction','Market Research','Campaign Management'], interview_stage_reached:'2nd round', interviews_completed:3, fee_percentage:8, referring_company:'MarketHire', strengths:'Led rebrand increasing brand awareness by 45%. Managed $5M+ annual budget.', gaps:'Less performance marketing integration.', feedback_summary:'Strategic brand leader.', recommendation:'Hire', why_not_hired:'Better fit selected', salary_expectation_min:140000, salary_expectation_max:165000, industry:'Marketing & Growth', status:'withdrawn', pii_redacted:true, source:'upload_form', full_name:'Chloe Williams', email:'chloe.w@test.com', current_employer:'Koala', current_job_title:'Senior Brand Manager' },
  { role_applied_for:'Project Manager', seniority_level:'Mid', years_experience:5, location_city:'Perth', location_country:'Australia', preferred_work_type:'On-site', skills:['Agile','Jira','Stakeholder Management','Budget Management','PMP'], interview_stage_reached:'2nd round', interviews_completed:3, fee_percentage:7, referring_company:'OpsHire', strengths:'Delivered $4M digital transformation on time and 8% under budget.', gaps:'Less distributed team experience.', feedback_summary:'Reliable PM with strong delivery record.', recommendation:'Hire', why_not_hired:'Better fit selected', salary_expectation_min:115000, salary_expectation_max:135000, industry:'Operations', status:'available', pii_redacted:true, source:'upload_form', full_name:'Nathan Kelly', email:'nathan.k@test.com', current_employer:'BHP', current_job_title:'Senior Project Manager' },
  { role_applied_for:'Enterprise Sales', seniority_level:'Senior', years_experience:8, location_city:'Sydney', location_country:'Australia', preferred_work_type:'On-site', skills:['Enterprise Sales','MEDDPICC','Salesforce','Strategic Accounts','C-suite Selling'], interview_stage_reached:'Final round', interviews_completed:5, fee_percentage:9, referring_company:'SalesHire', strengths:'Closed 3 deals worth $1M+ ARR each. Consistently top 3 performer.', gaps:null, feedback_summary:'Elite enterprise seller.', recommendation:'Strong hire', why_not_hired:'Offer declined', salary_expectation_min:180000, salary_expectation_max:220000, industry:'Sales & Revenue', status:'withdrawn', pii_redacted:true, source:'upload_form', full_name:'Patrick O Sullivan', email:'patrick.os@test.com', current_employer:'Salesforce', current_job_title:'Strategic Account Executive' },
]

export async function seedCandidates() {
  // Add unique IDs and timestamps, then store in localStorage
  const candidates = FAKE_CANDIDATES.map((c, i) => ({
    ...c,
    id: `candidate-${i + 1}`,
    created_at: new Date(Date.now() - Math.random() * 30 * 86400000).toISOString(),
    referred_at: new Date(Date.now() - Math.random() * 30 * 86400000).toISOString(),
  }))

  localStorage.setItem('pickt_candidates', JSON.stringify(candidates))
  console.log('[seed] Stored', candidates.length, 'candidates in localStorage')
  return { inserted: candidates.length, skipped: 0, total: candidates.length }
}

export function getCandidatesRaw() {
  const raw = localStorage.getItem('pickt_candidates')
  if (raw) {
    try { return JSON.parse(raw) } catch { /* fall through */ }
  }
  return null
}

/** Returns candidates with PII stripped (marketplace-safe). */
export function getCandidates() {
  const all = getCandidatesRaw()
  if (!all) return null
  return all.map(sanitizeForMarketplace)
}

/** Returns a single candidate with PII stripped (marketplace-safe). */
export function getCandidateById(id) {
  const all = getCandidatesRaw()
  const c = all?.find(c => c.id === id) || null
  return c ? sanitizeForMarketplace(c) : null
}

/**
 * Returns full candidate data including PII, but only if unlocked.
 * Still strips date_of_birth, gender, raw file URLs, interviewer_name.
 */
export function getCandidateWithPii(id) {
  if (!isUnlocked(id)) return getCandidateById(id)
  const all = getCandidatesRaw()
  const c = all?.find(c => c.id === id) || null
  return c ? sanitizeForProfile(c) : null
}

export { FAKE_CANDIDATES }
