import type { Industry } from "./discovery-options";

export type CandidateRecord = {
  id: string;
  industry: Industry;
  role_applied_for: string;
  seniority_level: string;
  years_experience: number;
  skills: string[];
  location_city: string;
  location_country: string;
  preferred_work_type: "Remote" | "Hybrid" | "On-site";
  interview_stage_reached: string;
  interviews_completed: number;
  referred_at: string;
  fee_percentage: number;
  referring_company: string;
};

/** ISO date strings for recency scoring */
export const CANDIDATES: CandidateRecord[] = [
  {
    id: "c1",
    industry: "Technology",
    role_applied_for: "Frontend Engineer",
    seniority_level: "Senior",
    years_experience: 6,
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS"],
    location_city: "London",
    location_country: "UK",
    preferred_work_type: "Remote",
    interview_stage_reached: "Final round",
    interviews_completed: 4,
    referred_at: "2026-03-28",
    fee_percentage: 8,
    referring_company: "Northwind Labs",
  },
  {
    id: "c2",
    industry: "Technology",
    role_applied_for: "Backend Engineer",
    seniority_level: "Mid",
    years_experience: 4,
    skills: ["Go", "PostgreSQL", "Kubernetes", "AWS"],
    location_city: "Berlin",
    location_country: "Germany",
    preferred_work_type: "Hybrid",
    interview_stage_reached: "Technical interview",
    interviews_completed: 3,
    referred_at: "2026-03-20",
    fee_percentage: 8,
    referring_company: "Acme SaaS",
  },
  {
    id: "c3",
    industry: "Technology",
    role_applied_for: "ML/AI Engineer",
    seniority_level: "Senior",
    years_experience: 7,
    skills: ["PyTorch", "Python", "MLOps", "CUDA"],
    location_city: "San Francisco",
    location_country: "US",
    preferred_work_type: "Remote",
    interview_stage_reached: "Final round",
    interviews_completed: 4,
    referred_at: "2026-03-29",
    fee_percentage: 9,
    referring_company: "Helix AI",
  },
  {
    id: "c4",
    industry: "Technology",
    role_applied_for: "DevOps/Cloud Engineer",
    seniority_level: "Lead",
    years_experience: 9,
    skills: ["Terraform", "AWS", "Kubernetes", "CI/CD"],
    location_city: "Dublin",
    location_country: "Ireland",
    preferred_work_type: "Hybrid",
    interview_stage_reached: "Final round",
    interviews_completed: 5,
    referred_at: "2026-03-15",
    fee_percentage: 8,
    referring_company: "CloudForge",
  },
  {
    id: "c5",
    industry: "Sales & Revenue",
    role_applied_for: "Account Executive",
    seniority_level: "Mid",
    years_experience: 5,
    skills: ["SaaS", "Enterprise", "Negotiation", "Salesforce"],
    location_city: "Austin",
    location_country: "US",
    preferred_work_type: "Hybrid",
    interview_stage_reached: "Final round",
    interviews_completed: 4,
    referred_at: "2026-03-27",
    fee_percentage: 7,
    referring_company: "Vertex CRM",
  },
  {
    id: "c6",
    industry: "Sales & Revenue",
    role_applied_for: "SDR/BDR",
    seniority_level: "Junior",
    years_experience: 2,
    skills: ["Outbound", "Cold calling", "HubSpot"],
    location_city: "Manchester",
    location_country: "UK",
    preferred_work_type: "On-site",
    interview_stage_reached: "On-site interview",
    interviews_completed: 2,
    referred_at: "2026-03-10",
    fee_percentage: 6,
    referring_company: "ScaleUp Co",
  },
  {
    id: "c7",
    industry: "Finance & FinTech",
    role_applied_for: "Financial Analyst",
    seniority_level: "Mid",
    years_experience: 4,
    skills: ["Excel", "SQL", "FP&A", "Modeling"],
    location_city: "New York",
    location_country: "US",
    preferred_work_type: "Hybrid",
    interview_stage_reached: "Final round",
    interviews_completed: 4,
    referred_at: "2026-03-29",
    fee_percentage: 8,
    referring_company: "FinStack",
  },
  {
    id: "c8",
    industry: "Finance & FinTech",
    role_applied_for: "FP&A",
    seniority_level: "Senior",
    years_experience: 8,
    skills: ["Planning", "Forecasting", "Tableau"],
    location_city: "Chicago",
    location_country: "US",
    preferred_work_type: "Remote",
    interview_stage_reached: "Technical interview",
    interviews_completed: 3,
    referred_at: "2026-03-05",
    fee_percentage: 8,
    referring_company: "LedgerOne",
  },
  {
    id: "c9",
    industry: "Marketing & Growth",
    role_applied_for: "Growth Marketer",
    seniority_level: "Senior",
    years_experience: 6,
    skills: ["Growth", "Experimentation", "Analytics"],
    location_city: "Amsterdam",
    location_country: "Netherlands",
    preferred_work_type: "Remote",
    interview_stage_reached: "Final round",
    interviews_completed: 4,
    referred_at: "2026-03-28",
    fee_percentage: 7,
    referring_company: "Bloom Media",
  },
  {
    id: "c10",
    industry: "Product & Design",
    role_applied_for: "Product Manager",
    seniority_level: "Senior",
    years_experience: 7,
    skills: ["Roadmaps", "Discovery", "Stakeholders"],
    location_city: "Seattle",
    location_country: "US",
    preferred_work_type: "Hybrid",
    interview_stage_reached: "Final round",
    interviews_completed: 4,
    referred_at: "2026-03-26",
    fee_percentage: 8,
    referring_company: "Orbit PM",
  },
  {
    id: "c11",
    industry: "Product & Design",
    role_applied_for: "UX/UI Designer",
    seniority_level: "Mid",
    years_experience: 4,
    skills: ["Figma", "Design systems", "Research"],
    location_city: "Toronto",
    location_country: "Canada",
    preferred_work_type: "Remote",
    interview_stage_reached: "Portfolio review",
    interviews_completed: 2,
    referred_at: "2026-03-22",
    fee_percentage: 8,
    referring_company: "Studio Nine",
  },
  {
    id: "c12",
    industry: "Operations",
    role_applied_for: "Operations Manager",
    seniority_level: "Lead",
    years_experience: 10,
    skills: ["Process", "Vendor mgmt", "OKRs"],
    location_city: "Singapore",
    location_country: "Singapore",
    preferred_work_type: "Hybrid",
    interview_stage_reached: "Final round",
    interviews_completed: 5,
    referred_at: "2026-03-18",
    fee_percentage: 8,
    referring_company: "OpsWorks",
  },
  {
    id: "c13",
    industry: "Data & Analytics",
    role_applied_for: "Data Scientist",
    seniority_level: "Senior",
    years_experience: 6,
    skills: ["Python", "Statistics", "Causal inference"],
    location_city: "Boston",
    location_country: "US",
    preferred_work_type: "Remote",
    interview_stage_reached: "Final round",
    interviews_completed: 4,
    referred_at: "2026-03-29",
    fee_percentage: 9,
    referring_company: "DataNest",
  },
  {
    id: "c14",
    industry: "Data & Analytics",
    role_applied_for: "Data Engineer",
    seniority_level: "Mid",
    years_experience: 4,
    skills: ["Spark", "Airflow", "Snowflake"],
    location_city: "Warsaw",
    location_country: "Poland",
    preferred_work_type: "Remote",
    interview_stage_reached: "Technical interview",
    interviews_completed: 3,
    referred_at: "2026-03-12",
    fee_percentage: 8,
    referring_company: "Pipehouse",
  },
  {
    id: "c15",
    industry: "People & HR",
    role_applied_for: "Talent Acquisition",
    seniority_level: "Mid",
    years_experience: 5,
    skills: ["Sourcing", "ATS", "Employer brand"],
    location_city: "Dublin",
    location_country: "Ireland",
    preferred_work_type: "Hybrid",
    interview_stage_reached: "Final round",
    interviews_completed: 4,
    referred_at: "2026-03-25",
    fee_percentage: 7,
    referring_company: "PeopleFirst",
  },
  {
    id: "c16",
    industry: "Customer Success",
    role_applied_for: "Customer Success Manager",
    seniority_level: "Senior",
    years_experience: 6,
    skills: ["Renewals", "QBRs", "SaaS metrics"],
    location_city: "Denver",
    location_country: "US",
    preferred_work_type: "Remote",
    interview_stage_reached: "Final round",
    interviews_completed: 4,
    referred_at: "2026-03-27",
    fee_percentage: 7,
    referring_company: "RetainHQ",
  },
  {
    id: "c17",
    industry: "Legal & Compliance",
    role_applied_for: "Legal Counsel",
    seniority_level: "Senior",
    years_experience: 8,
    skills: ["Commercial", "Privacy", "Negotiation"],
    location_city: "London",
    location_country: "UK",
    preferred_work_type: "Hybrid",
    interview_stage_reached: "Final round",
    interviews_completed: 4,
    referred_at: "2026-03-21",
    fee_percentage: 10,
    referring_company: "Lex Partners",
  },
  {
    id: "c18",
    industry: "Technology",
    role_applied_for: "Software Engineer",
    seniority_level: "Mid",
    years_experience: 3,
    skills: ["Java", "Spring", "Microservices"],
    location_city: "Bengaluru",
    location_country: "India",
    preferred_work_type: "Remote",
    interview_stage_reached: "On-site interview",
    interviews_completed: 2,
    referred_at: "2026-03-08",
    fee_percentage: 8,
    referring_company: "TechGrid",
  },
  {
    id: "c19",
    industry: "Technology",
    role_applied_for: "Security Engineer",
    seniority_level: "Senior",
    years_experience: 7,
    skills: ["AppSec", "Threat modeling", "AWS"],
    location_city: "Tel Aviv",
    location_country: "Israel",
    preferred_work_type: "Hybrid",
    interview_stage_reached: "Final round",
    interviews_completed: 4,
    referred_at: "2026-03-30",
    fee_percentage: 9,
    referring_company: "ShieldSec",
  },
  {
    id: "c20",
    industry: "Marketing & Growth",
    role_applied_for: "Head of Marketing",
    seniority_level: "Director",
    years_experience: 12,
    skills: ["GTM", "Brand", "Leadership"],
    location_city: "Paris",
    location_country: "France",
    preferred_work_type: "Hybrid",
    interview_stage_reached: "Final round",
    interviews_completed: 5,
    referred_at: "2026-03-24",
    fee_percentage: 9,
    referring_company: "Maison Growth",
  },
  {
    id: "c21",
    industry: "Sales & Revenue",
    role_applied_for: "Head of Sales",
    seniority_level: "Director",
    years_experience: 14,
    skills: ["Leadership", "Enterprise", "GTM"],
    location_city: "Sydney",
    location_country: "Australia",
    preferred_work_type: "Hybrid",
    interview_stage_reached: "Final round",
    interviews_completed: 5,
    referred_at: "2026-03-17",
    fee_percentage: 9,
    referring_company: "RevenueCo",
  },
  {
    id: "c22",
    industry: "Product & Design",
    role_applied_for: "UX Researcher",
    seniority_level: "Mid",
    years_experience: 4,
    skills: ["Studies", "Usability", "Insights"],
    location_city: "Copenhagen",
    location_country: "Denmark",
    preferred_work_type: "Remote",
    interview_stage_reached: "Technical interview",
    interviews_completed: 3,
    referred_at: "2026-03-11",
    fee_percentage: 8,
    referring_company: "Insight Lab",
  },
  {
    id: "c23",
    industry: "Data & Analytics",
    role_applied_for: "Analytics Engineer",
    seniority_level: "Senior",
    years_experience: 6,
    skills: ["dbt", "Looker", "SQL"],
    location_city: "Melbourne",
    location_country: "Australia",
    preferred_work_type: "Remote",
    interview_stage_reached: "Final round",
    interviews_completed: 4,
    referred_at: "2026-03-29",
    fee_percentage: 8,
    referring_company: "MetricFlow",
  },
  {
    id: "c24",
    industry: "Technology",
    role_applied_for: "Platform Engineer",
    seniority_level: "Lead",
    years_experience: 9,
    skills: ["K8s", "Go", "Observability"],
    location_city: "Stockholm",
    location_country: "Sweden",
    preferred_work_type: "Hybrid",
    interview_stage_reached: "Final round",
    interviews_completed: 4,
    referred_at: "2026-03-23",
    fee_percentage: 8,
    referring_company: "PlatformIO",
  },
];
