export const INDUSTRIES = [
  "Technology",
  "Sales & Revenue",
  "Finance & FinTech",
  "Marketing & Growth",
  "Product & Design",
  "Operations",
  "Data & Analytics",
  "People & HR",
  "Customer Success",
  "Legal & Compliance",
] as const;

export type Industry = (typeof INDUSTRIES)[number];

export const ROLES_BY_INDUSTRY: Record<Industry, readonly string[]> = {
  Technology: [
    "Software Engineer",
    "Solutions Architect",
    "DevOps/Cloud Engineer",
    "Security Engineer",
    "Mobile Engineer",
    "Frontend Engineer",
    "Backend Engineer",
    "ML/AI Engineer",
    "Platform Engineer",
    "QA/Test Engineer",
  ],
  "Sales & Revenue": [
    "Account Executive",
    "SDR/BDR",
    "Head of Sales",
    "Enterprise Sales",
    "Partnerships Manager",
    "Sales Operations",
    "Revenue Operations",
    "Regional Sales Director",
  ],
  "Finance & FinTech": [
    "Financial Analyst",
    "CFO/Finance Director",
    "Finance Manager",
    "FP&A",
    "Risk & Compliance",
    "FinTech Product",
    "Accountant",
  ],
  "Marketing & Growth": [
    "Growth Marketer",
    "Performance Marketing",
    "Content/SEO",
    "Social Media",
    "Brand Manager",
    "CRM/Email",
    "Head of Marketing",
    "Marketing Analyst",
  ],
  "Product & Design": [
    "Product Manager",
    "UX/UI Designer",
    "UX Researcher",
    "Product Designer",
    "Head of Product",
    "Design Lead",
    "Mobile Product",
  ],
  Operations: [
    "Operations Manager",
    "COO",
    "Supply Chain",
    "Project Manager",
    "Process Improvement",
    "Logistics",
  ],
  "Data & Analytics": [
    "Data Analyst",
    "Data Scientist",
    "Data Engineer",
    "Analytics Engineer",
    "ML Engineer",
    "BI Developer",
    "Head of Data",
  ],
  "People & HR": [
    "Talent Acquisition",
    "HR Business Partner",
    "People Ops",
    "L&D Manager",
    "Chief People Officer",
    "Compensation & Benefits",
  ],
  "Customer Success": [
    "Customer Success Manager",
    "Account Manager",
    "Head of CS",
    "Support Lead",
    "Renewals Manager",
    "CS Operations",
  ],
  "Legal & Compliance": [
    "General Counsel",
    "Legal Counsel",
    "Compliance Manager",
    "Contract Manager",
    "Privacy/GDPR",
  ],
};

export const SENIORITY_OPTIONS = [
  "Junior (0–2 yrs)",
  "Mid-level (3–5 yrs)",
  "Senior (5–8 yrs)",
  "Lead/Principal",
  "Head of/Director",
  "VP/C-suite",
  "Any level — show all",
] as const;

export type SeniorityOption = (typeof SENIORITY_OPTIONS)[number];
